### PR TITLE
Use the correct deployment manifest for the operator

### PR DESCRIPTION
**Pull request by bpradipt**
Signed-off-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>

### CODE REVIEW

**Comment by dcmiddle** [comment]
This looks like this changes the directions in `main` to reference the deploy.yaml in the `ccv0-branch`. Is that intended?

**Comment by bpradipt** [comment]
> This looks like this changes the directions in `main` to reference the deploy.yaml in the `ccv0-branch`. Is that intended?

@dcmiddle yes, this is intentional to ensure the existing demo works as is. The code in main has deviated significantly and the existing demo will not work.

**Review by ariel-adam — APPROVED** [review]
Looks good and important to be able to run this demo

**Comment by mythi** [comment]
> > This looks like this changes the directions in `main` to reference the deploy.yaml in the `ccv0-branch`. Is that intended?
> 
> @dcmiddle yes, this is intentional to ensure the existing ssh-demo works for folks following the given instructions. The code in main has deviated significantly and the existing ssh-demo will not work when using `main`.

I'd suggest to add this to the commit message.

**Review by sameo — APPROVED** [review]

**Comment by sameo** [comment]
@bpradipt Could you please amend the commit message so we can merge that PR, please?

**Comment by bpradipt** [comment]
> @bpradipt Could you please amend the commit message so we can merge that PR, please?

@sameo I have updated the commit message.

**Comment by dcmiddle** [comment]
I don't oppose this being merged, but just for clarity, when would we switch the directions in main back to main xor why would we not point demo users to the directions in the ccv0 branch.

**Review by mythi — APPROVED** [review]
/lgtm

**Pull request merged**
