### PR TITLE
ssh-demo: Update runtimeClassName

### PR DESCRIPTION
**Pull request by stevenhorsman**
Update runtimeClassName from kata-cc to kata to reflect the operator changes

Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
> > @bpradipt - I think that we moved away from `kata-cc` to `kata` for the default runtime class name a while ago?
> 
> @stevenhorsman the ssh-demo uses the old operator code from ccv0-demo branch. The operator binary and the payload points to ccv0. Once the new ssh payload is there, we can update the instructions to use the latest operator code (deploy.yaml) and the payload.

Ah ok, maybe this wasn't a good change to make yet. I was hoping that we could re-use the kubernetes yaml file from this in the new documentation, but maybe we're not ready for that until the sample payload is available.

**Review by dcmiddle — APPROVED** [review]

**Review by fitzthum — APPROVED** [review]
This seems good to me. 

@bpradipt mentions something about the SSH demo using the old operator. I don't really remember how this worked. It seems like these instructions don't say anything about the operator. They just tell someone how to build a container image and deploy it. It seems like a good idea to use a runtime class that will work.

**Comment by bpradipt** [comment]
> This seems good to me.
> 
> @bpradipt mentions something about the SSH demo using the old operator. I don't really remember how this worked. It seems like these instructions don't say anything about the operator. They just tell someone how to build a container image and deploy it. It seems like a good idea to use a runtime class that will work.

Jakob had built the initial ssh-demo payload using the first code drop for ccv0 branch. Also, the manifests used were specific to the old operator code (before v0.1.0). Now we have the latest ssh-demo payload built by Steve and it works with the latest operator code, so this change is good..

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @stevenhorsman

**Pull request merged**
