### PR TITLE
Fix trust model persona doc indentation

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Review by dcmiddle — APPROVED** [review]

**Review by magowan — APPROVED** [review]
Did you use IDE settings or a tool ? Just figuring I should setup my IDE or run same tool in future?
Thanks

**Comment by dcmiddle** [comment]
vim
:set list

**Comment by surajssd** [comment]
Who can hit the merge button 😉 ?

**Comment by dcmiddle** [comment]
> Who can hit the merge button 😉 ?

Only vim users ;)

**Pull request merged**
